/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-bright": "#f9f9f9",
        "surface-dim": "#dadada",
        "surface-variant": "#e2e2e2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f3f3",
        "surface-container": "#eeeeee",
        "surface-container-high": "#e8e8e8",
        "surface-container-highest": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-surface-variant": "#42493e",
        "inverse-surface": "#2f3131",
        "inverse-on-surface": "#f0f1f1",
        outline: "#72796e",
        "outline-variant": "#c2c9bb",
        "surface-tint": "#3b6934",
        primary: "#154212",
        "on-primary": "#ffffff",
        "primary-container": "#2d5a27",
        "on-primary-container": "#9dd090",
        "inverse-primary": "#a1d494",
        "primary-fixed": "#bcf0ae",
        "primary-fixed-dim": "#a1d494",
        "on-primary-fixed": "#002201",
        "on-primary-fixed-variant": "#23501e",
        secondary: "#77574d",
        "on-secondary": "#ffffff",
        "secondary-container": "#fed3c7",
        "on-secondary-container": "#795950",
        "secondary-fixed": "#ffdbd0",
        "secondary-fixed-dim": "#e7bdb1",
        "on-secondary-fixed": "#2c160e",
        "on-secondary-fixed-variant": "#5d4037",
        tertiary: "#5a2e00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#7b4101",
        "on-tertiary-container": "#ffb271",
        "tertiary-fixed": "#ffdcc3",
        "tertiary-fixed-dim": "#ffb77d",
        "on-tertiary-fixed": "#2f1500",
        "on-tertiary-fixed-variant": "#6e3900",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9f9",
        "on-background": "#1a1c1c",
        beige: "#f5f5dc",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      spacing: {
        base: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "stack-sm": "4px",
        "stack-md": "12px",
        "stack-lg": "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        display: ["Montserrat", "sans-serif"],
        headline: ["Montserrat", "sans-serif"],
        body: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-lg-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
      },
      boxShadow: {
        ambient: "0 4px 20px -4px rgba(93, 64, 55, 0.15)",
        "ambient-lg": "0 10px 40px -8px rgba(93, 64, 55, 0.2)",
      },
    },
  },
  plugins: [],
};
